print('Numele Prenumele:         Stici Vasile')
print('Data, luna, anul nașterii:        3 August 2004')
print('Locul nașteri:         Municipiul Bălți')
print('Naționalitatea:         Moldovean')
print('Numele Prenumele Părinților:    Ion Stici  și  Galina Stici')
print('Locul de studiu:   Liceul Teoretic ,,Mihai Eminescu" din Bălți, clasa a X-a "C" ')
print('Hobby-uri:    Fotbal, Jocul de dame, Filmele action, Plimbările cu prietenii și Petrecerea timpului cu familia')
print('Studii:   1)Clasele primare în I.P.L.T. ,,Mihai Eminescu" 2011-2015')
print('          2)Gimnaziul în I.P.L.T. ,,Mihai Eminescu" 2015-2020')
print('Anii de liceu în I.P.L.T.,,Mihai Eminescu" 2020-2023')
print('Obiective: Intrarea la Facultatea de Drept din Vest din Timișoara sau Intrarea la Universitatea de Informatică din București')
print('Materiile preferate:    Matematica, Informatica, Istoria, Educația fizică, Chimia, Fizica')